name: Performance regression check

on:
  pull_request:
    branches:
      - master
      - '*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  bench:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Install minimal nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          default: true

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "v0-recs-benches"

      - run: /home/runner/.cargo/bin/cargo -V

      - uses: boa-dev/criterion-compare-action@v3
        with:
          # The name of the branch to compare with.
          branchName: ${{ github.base_ref }}
